export { default as RegisterLayout } from './RegisterLayout'
export { default as PhoneScreen } from './PhoneScreen'
export { default as OTPScreen } from './OTPScreen'
export { default as BasicInfoScreen } from './BasicInfoScreen'
export { default as NafathScreen } from './NafathScreen'
